DEFAULT_BOARD = {
    "columns": [
        {
            "id": "col-backlog",
            "title": "Backlog",
            "color": "#3B82F6",
            "icon": "inbox",
            "cardIds": ["card-1", "card-2"],
        },
        {
            "id": "col-discovery",
            "title": "Discovery",
            "color": "#8B5CF6",
            "icon": "search",
            "cardIds": ["card-3"],
        },
        {
            "id": "col-progress",
            "title": "In Progress",
            "color": "#EC4899",
            "icon": "play",
            "cardIds": ["card-4", "card-5"],
        },
        {
            "id": "col-review",
            "title": "Review",
            "color": "#EF4444",
            "icon": "eye",
            "cardIds": ["card-6"],
        },
        {
            "id": "col-done",
            "title": "Done",
            "color": "#F97316",
            "icon": "check-circle",
            "cardIds": ["card-7", "card-8"],
        },
    ],
    "cards": {
        "card-1": {
            "id": "card-1",
            "title": "Align roadmap themes",
            "details": "Draft quarterly themes with impact statements and metrics.",
            "priority": "high",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-2": {
            "id": "card-2",
            "title": "Gather customer signals",
            "details": "Review support tags, sales notes, and churn feedback.",
            "priority": "medium",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-3": {
            "id": "card-3",
            "title": "Prototype analytics view",
            "details": "Sketch initial dashboard layout and key drill-downs.",
            "priority": "critical",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-4": {
            "id": "card-4",
            "title": "Refine status language",
            "details": "Standardize column labels and tone across the board.",
            "priority": "medium",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-5": {
            "id": "card-5",
            "title": "Design card layout",
            "details": "Add hierarchy and spacing for scanning dense lists.",
            "priority": "high",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-6": {
            "id": "card-6",
            "title": "QA micro-interactions",
            "details": "Verify hover, focus, and loading states.",
            "priority": "critical",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-7": {
            "id": "card-7",
            "title": "Ship marketing page",
            "details": "Final copy approved and asset pack delivered.",
            "priority": "low",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
        "card-8": {
            "id": "card-8",
            "title": "Close onboarding sprint",
            "details": "Document release notes and share internally.",
            "priority": "low",
            "dueDate": None,
            "labelIds": [],
            "comments": [],
        },
    },
    "labels": [],
}


BOARD_TEMPLATES = {
    "blank": {
        "columns": [
            {
                "id": "col-todo",
                "title": "To Do",
                "color": "#3B82F6",
                "icon": "inbox",
                "cardIds": [],
            },
        ],
        "cards": {},
        "labels": [],
    },
    "kanban": DEFAULT_BOARD,
    "scrum": {
        "columns": [
            {
                "id": "col-product-backlog",
                "title": "Product Backlog",
                "color": "#64748B",
                "icon": "inbox",
                "cardIds": [],
            },
            {
                "id": "col-sprint-backlog",
                "title": "Sprint Backlog",
                "color": "#3B82F6",
                "icon": "target",
                "cardIds": [],
            },
            {
                "id": "col-in-progress",
                "title": "In Progress",
                "color": "#EC4899",
                "icon": "play",
                "cardIds": [],
            },
            {
                "id": "col-testing",
                "title": "Testing",
                "color": "#EAB308",
                "icon": "eye",
                "cardIds": [],
            },
            {
                "id": "col-done",
                "title": "Done",
                "color": "#22C55E",
                "icon": "check-circle",
                "cardIds": [],
            },
        ],
        "cards": {},
        "labels": [
            {"id": "lbl-story", "name": "Story", "color": "#3B82F6"},
            {"id": "lbl-bug", "name": "Bug", "color": "#EF4444"},
            {"id": "lbl-task", "name": "Task", "color": "#22C55E"},
            {"id": "lbl-spike", "name": "Spike", "color": "#8B5CF6"},
        ],
    },
    "bug-tracking": {
        "columns": [
            {
                "id": "col-reported",
                "title": "Reported",
                "color": "#EF4444",
                "icon": "flame",
                "cardIds": [],
            },
            {
                "id": "col-confirmed",
                "title": "Confirmed",
                "color": "#F97316",
                "icon": "shield",
                "cardIds": [],
            },
            {
                "id": "col-in-progress",
                "title": "In Progress",
                "color": "#3B82F6",
                "icon": "play",
                "cardIds": [],
            },
            {
                "id": "col-fixed",
                "title": "Fixed",
                "color": "#22C55E",
                "icon": "check-circle",
                "cardIds": [],
            },
            {
                "id": "col-closed",
                "title": "Closed",
                "color": "#64748B",
                "icon": "archive",
                "cardIds": [],
            },
        ],
        "cards": {},
        "labels": [
            {"id": "lbl-crash", "name": "Crash", "color": "#EF4444"},
            {"id": "lbl-ui", "name": "UI", "color": "#8B5CF6"},
            {"id": "lbl-perf", "name": "Performance", "color": "#F97316"},
            {"id": "lbl-security", "name": "Security", "color": "#EAB308"},
        ],
    },
}
